### ISSUE TITLE
Update existing registrations?

### ISSUE THREAD

**Issue by emanjon** [jedisct1/draft-denis-tls-aegis#1]
If the AEGIS RFC removed the IANA registrations for 

TLS_AEGIS_256_SHA512
TLS_AEGIS_128L_SHA256

it might be a good idea to uodate the reference in IANA to point to this document.

**Comment by jedisct1** [comment]
Hi John,

IANA didn't remove the code points; they point to the previous revision of the AEGIS draft.

What we can do is finish a first version of this document, propose it to the TLS WG, and if it is accepted, ask IANA to update them.

**Comment by jedisct1** [comment]
A first version of the document can be seen here: https://jedisct1.github.io/draft-denis-tls-aegis/draft-denis-tls-aegis.html

Your input is more that welcome.
