### ISSUE TITLE
Are examples useful?

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/draft-denis-tls-aegis#2]
Adding AEGIS to existing TLS libraries shouldn't be difficult.

Still, there are differences with other cipher suites:

- The nonce sizes (128 and 256 bits), whereas other ciphers use a 96 bit nonce, and implementations may be designed around that assumption.
- Usage of SHA512 for key derivation, so secrets are bigger too.

Making these differences obvious was one of the goals of having these examples.

But maybe they are not necessary, especially the ones about nonce computation.

**Comment by samuel-lucas6** [comment]
They probably aren't necessary, but I think we can keep them in unless we're told to remove them.

**Comment by jedisct1** [comment]
Sounds good, especially now that the nonce derivation examples are gone.
