### ISSUE TITLE
Should nonce_len be in bits?

### ISSUE THREAD

**Issue by samuel-lucas6** [jedisct1/draft-denis-tls-aegis#6]
In Sections 4/5, should `nonce_len` be in bits since the `ZeroPad()` function takes the second parameter in bits?

> nonce_len: the AEGIS nonce length, either 16 or 32, depending on the chosen AEAD algorithm.
> 
> A 48-bit mask is computed as follows:
> 
> mask = Stream(48, sn_key, ZeroPad(ciphertext[0..16], nonce_len))

From the AEGIS draft:

> ZeroPad(x, n): padding operation. Trailing zeros are concatenated to x until the total length is a multiple of n bits.

**Comment by jedisct1** [comment]
Good catch! Yes, having them in bits totally makes sense.
